name: Deploy Telegram Bot

on:
  # Запуск при пуше в main ветку
  push:
    branches: [ main, master ]
  
  # Запуск по расписанию (каждые 5 минут)
  schedule:
    - cron: '*/5 * * * *'
  
  # Ручной запуск из интерфейса GitHub
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" > .env
        echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
        
    - name: Run bot for 5 minutes
      run: |
        # Запускаем бота на 295 секунд (почти 5 минут)
        timeout 295 python bot.py || echo "Bot session finished"
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: bot-logs
        path: |
          *.log
